#!/bin/sh

TESTDIR="./Test/*"
EXDIR="Test_ex"

mkdir $EXDIR
for f in $TESTDIR
do
	NAME=$(echo $f | cut -c 8- | rev | cut -c 3- |rev)
	gcc $f -o $EXDIR/$NAME -L./ libft_malloc.so -I Includes -lpthread
done